### ISSUE TITLE
CMake builds

### ISSUE THREAD

**Issue by kiranpradeep** [wirepas/c-mesh-api#14]
I was using this library and felt CMake would have helped with IDEs in navigation and builds platforms like macOS (when platform support is added in future). Is usage of Makefile over CMakeLists intentional? If not, shall I submit a pull request?

**Comment by GwendalRaoul** [comment]
Makefile was used at the beginning of project as target was only Linux system.
But you are right that it could help in future when other platform are supported. I guess it could be the right time to consider it.
For now as only Linux is supported, it will not have a high priority.
