### ISSUE TITLE
comparison of uint8_t with constant 256

### ISSUE THREAD

**Issue by kiranpradeep** [wirepas/c-mesh-api#15]
In dsap.c[[1](https://github.com/wirepas/c-mesh-api/blob/60343e0d5e15a073927711a6f336fc46aed6cb7e/lib/wpc/dsap.c#L250)], there is a comparison between uint8_t and constant 256 which is always true. Is this intentional?

**Comment by GwendalRaoul** [comment]
Yes it is intentional. Main reason is that the 256 value is a constant that could be reduced in future if we want to reduce the number of EP to register.
I guess it generates you a warning by your compiler.
I can see two options to fix it:
    - Remove the test completely. It could lead to bugs in future if constant has a value lower than 256, but it will probably never happen
    - cast the variable to an uint16_t

I think, the first option is fine
