### ISSUE TITLE
[BUG]  WPC_get_app_config_data returns APP_RES_INVALID_VALUE when size is bigger than max_size

### ISSUE THREAD

**Issue by vladuttuhutintemo** [wirepas/c-mesh-api#35]
**Describe the bug**
WPC_get_app_config_data returns APP_RES_INVALID_VALUE when size is bigger than max_size. 

**Expected behavior**
The error should be returned when the buffer is too small not when is too big. The fact that the buffer is bigger than needed should not be a problem.

**Comment by GwendalRaoul** [comment]
Thanks for opening this bug!
Yes it is clearly a bug. Fix is on review.
